# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13cP-2kIYeRxBp4KRgJje3d2lmrPw38g4
"""

import matplotlib.pyplot as plt
import numpy as np
x = np.array(["60-24", "61-24","630-24","631-24",])
y = np.array([21,19,22,25])
plt.bar(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x = np.array(["60-24", "61-24","630-24","631-24",])
y = np.array([21,19,22,25])
plt.barh(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x =np.array([85,90,90,92,95])
mylabels = ["AI", "CS", "CHIZIQLI ALGEBRA" , "DISKRETLIK", "SXEMALAR"]
myexplode = [0.2, 0, 0, 0, 0]
mycolors = ["darkred", "darkgreen", "darkblue", "#8043A8", "pink"]
plt.pie(x, labels=mylabels, startangle=90, explode=myexplode, shadow=True, colors=mycolors)
plt.legend(title="Fanlar")

plt.show()